export enum Sender {
  User = 'user',
  AI = 'ai',
}

export interface ImageAttachment {
  mimeType: string;
  data: string; // Base64 string
}

export interface GeneratedImage {
  id: string;
  data: string; // Base64
  prompt: string;
  timestamp: number;
}

export interface Message {
  id: string;
  sender: Sender;
  text?: string;
  attachments?: ImageAttachment[]; // Images sent by user
  generatedImages?: GeneratedImage[]; // Images generated by AI
  timestamp: number;
}

export interface GeminiConfig {
  model: string;
}