import { GoogleGenAI, Modality } from "@google/genai";
import { ImageAttachment } from "../types";

const API_KEY = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey: API_KEY });

// Using the Flash Image model as requested for "Nano banana" style editing and generation
const MODEL_NAME = 'gemini-2.5-flash-image';

/**
 * Generates or edits an image based on a prompt and optional reference images.
 */
export const generateOrEditImage = async (
  prompt: string,
  referenceImage?: ImageAttachment
): Promise<string[]> => {
  if (!API_KEY) {
    throw new Error("API Key not found. Please check your environment variables.");
  }

  try {
    const parts: any[] = [];

    // If there is a reference image, this becomes an "Edit" or "Variation" task
    if (referenceImage) {
      parts.push({
        inlineData: {
          data: referenceImage.data,
          mimeType: referenceImage.mimeType,
        },
      });
    }

    // Add the text prompt
    parts.push({ text: prompt });

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: parts,
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const generatedImages: string[] = [];

    // Parse response for image data
    if (response.candidates && response.candidates.length > 0) {
      const content = response.candidates[0].content;
      if (content && content.parts) {
        for (const part of content.parts) {
          if (part.inlineData && part.inlineData.data) {
            generatedImages.push(part.inlineData.data);
          }
        }
      }
    }

    if (generatedImages.length === 0) {
      throw new Error("No images were generated by the model.");
    }

    return generatedImages;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

/**
 * Helper to convert a File object to Base64
 */
export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
        // Remove the Data-URL prefix (e.g. "data:image/png;base64,")
        const result = reader.result as string;
        const base64 = result.split(',')[1];
        resolve(base64);
    };
    reader.onerror = (error) => reject(error);
  });
};